export const productos = [
  {
    id: 1,
    nombre: "Smartphone Galaxy S23",
    descripcion: "Smartphone de última generación con cámara de alta resolución",
    descripcionLarga:
      "El Galaxy S23 es un smartphone de última generación que ofrece un rendimiento excepcional. Con su potente procesador y su cámara de alta resolución, podrás capturar momentos increíbles y disfrutar de una experiencia fluida en cualquier aplicación.",
    precio: 899.99,
    descuento: 10,
    categoria: "electronica",
    marca: "samsung",
    imagen: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop",
    especificaciones: [
      "Pantalla AMOLED de 6.1 pulgadas",
      "Procesador Snapdragon 8 Gen 2",
      "Cámara principal de 50MP",
      "Batería de 3900mAh",
      "Android 13",
    ],
    tiendaId: 1,
    tipoVenta: "directa",
    stock: 15,
    tiempoEntrega: "Inmediato",
  },
  {
    id: 2,
    nombre: "Laptop ProBook X360",
    descripcion: "Laptop convertible con pantalla táctil y procesador de última generación",
    descripcionLarga:
      "La ProBook X360 es una laptop convertible que combina potencia y versatilidad. Su pantalla táctil te permite utilizarla como tablet, y su potente procesador te garantiza un rendimiento excepcional en cualquier tarea.",
    precio: 1299.99,
    descuento: 0,
    categoria: "electronica",
    marca: "hp",
    imagen: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
    especificaciones: [
      "Pantalla táctil de 13.3 pulgadas",
      "Procesador Intel Core i7",
      "16GB de RAM",
      "512GB SSD",
      "Windows 11 Pro",
    ],
    tiendaId: 1,
    tipoVenta: "pedido",
    stock: 0,
    tiempoEntrega: "7-10 días hábiles",
  },
  {
    id: 3,
    nombre: "Zapatillas Running Pro",
    descripcion: "Zapatillas de running con tecnología de amortiguación avanzada",
    descripcionLarga:
      "Las Zapatillas Running Pro están diseñadas para ofrecer el máximo rendimiento y comodidad durante tus carreras. Su tecnología de amortiguación avanzada reduce el impacto en cada pisada, y su diseño ligero te permite alcanzar tu máxima velocidad.",
    precio: 129.99,
    descuento: 20,
    categoria: "deportes",
    marca: "nike",
    imagen: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    especificaciones: [
      "Tecnología de amortiguación React",
      "Parte superior de malla transpirable",
      "Suela de goma duradera",
      "Peso: 255g",
      "Disponible en varios colores",
    ],
    tiendaId: 4,
    tipoVenta: "directa",
    stock: 8,
    tiempoEntrega: "Inmediato",
  },
  {
    id: 4,
    nombre: 'Smart TV 4K 55"',
    descripcion: "Televisor inteligente con resolución 4K y asistente de voz integrado",
    descripcionLarga:
      "Este Smart TV 4K de 55 pulgadas ofrece una calidad de imagen excepcional con colores vibrantes y detalles nítidos. Su sistema operativo inteligente te permite acceder a tus aplicaciones de streaming favoritas, y su asistente de voz integrado te facilita el control del televisor.",
    precio: 699.99,
    descuento: 15,
    categoria: "electronica",
    marca: "sony",
    imagen: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop",
    especificaciones: [
      "Pantalla LED 4K de 55 pulgadas",
      "HDR10+ y Dolby Vision",
      "Sistema operativo Android TV",
      "Asistente de Google integrado",
      "3 puertos HDMI y 2 puertos USB",
    ],
    tiendaId: 6,
    tipoVenta: "directa",
    stock: 3,
    tiempoEntrega: "Inmediato",
  },
  {
    id: 5,
    nombre: "Camiseta Deportiva DryFit",
    descripcion: "Camiseta deportiva con tecnología de secado rápido",
    descripcionLarga:
      "La Camiseta Deportiva DryFit está diseñada para mantenerte fresco y seco durante tus entrenamientos. Su tecnología de secado rápido absorbe el sudor y lo evapora rápidamente, mientras que su tejido ligero y transpirable te proporciona la máxima comodidad.",
    precio: 34.99,
    descuento: 0,
    categoria: "ropa",
    marca: "adidas",
    imagen: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop",
    especificaciones: [
      "Tecnología DryFit para secado rápido",
      "Tejido 100% poliéster reciclado",
      "Diseño sin costuras para mayor comodidad",
      "Protección UV UPF 40+",
      "Disponible en varios colores y tallas",
    ],
    tiendaId: 4,
    tipoVenta: "directa",
    stock: 25,
    tiempoEntrega: "Inmediato",
  },
  {
    id: 6,
    nombre: "Robot Aspirador Inteligente",
    descripcion: "Robot aspirador con mapeo láser y control por aplicación",
    descripcionLarga:
      "El Robot Aspirador Inteligente facilita la limpieza de tu hogar con su avanzado sistema de navegación láser. Puede mapear tu casa, programar limpiezas automáticas y controlarse desde tu smartphone. Su potente succión elimina eficazmente el polvo y la suciedad de cualquier tipo de suelo.",
    precio: 349.99,
    descuento: 5,
    categoria: "hogar",
    marca: "xiaomi",
    imagen: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    especificaciones: [
      "Navegación láser LDS",
      "Potencia de succión de 2500Pa",
      "Batería de 5200mAh (150 min de autonomía)",
      "Control por aplicación móvil",
      "Compatible con asistentes de voz",
    ],
    tiendaId: 3,
    tipoVenta: "pedido",
    stock: 0,
    tiempoEntrega: "5-7 días hábiles",
  },
  {
    id: 7,
    nombre: "Auriculares Inalámbricos Pro",
    descripcion: "Auriculares inalámbricos con cancelación activa de ruido",
    descripcionLarga:
      "Los Auriculares Inalámbricos Pro ofrecen una experiencia de audio inmersiva con su avanzada tecnología de cancelación de ruido. Su diseño ergonómico garantiza un ajuste cómodo durante horas, y su batería de larga duración te permite disfrutar de tu música favorita todo el día.",
    precio: 199.99,
    descuento: 0,
    categoria: "electronica",
    marca: "apple",
    imagen: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    especificaciones: [
      "Cancelación activa de ruido",
      "Hasta 20 horas de autonomía",
      "Conectividad Bluetooth 5.0",
      "Resistencia al agua IPX4",
      "Micrófono integrado para llamadas",
    ],
    tiendaId: 1,
    tipoVenta: "directa",
    stock: 12,
    tiempoEntrega: "Inmediato",
  },
  {
    id: 8,
    nombre: "Crema Hidratante Facial",
    descripcion: "Crema hidratante con ácido hialurónico y vitamina C",
    descripcionLarga:
      "La Crema Hidratante Facial proporciona una hidratación intensa y duradera gracias a su fórmula enriquecida con ácido hialurónico. La vitamina C ayuda a iluminar el tono de la piel y a reducir los signos del envejecimiento, dejando tu piel radiante y rejuvenecida.",
    precio: 29.99,
    descuento: 0,
    categoria: "belleza",
    marca: "loreal",
    imagen: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop",
    especificaciones: [
      "Fórmula con ácido hialurónico y vitamina C",
      "Hidratación de 48 horas",
      "Textura ligera no grasa",
      "Apta para todo tipo de piel",
      "Dermatológicamente testada",
    ],
    tiendaId: 5,
    tipoVenta: "directa",
    stock: 30,
    tiempoEntrega: "Inmediato",
  },
  {
    id: 9,
    nombre: "Bicicleta de Montaña Pro",
    descripcion: "Bicicleta de montaña con cuadro de aluminio y suspensión delantera",
    descripcionLarga:
      "La Bicicleta de Montaña Pro está diseñada para los amantes del ciclismo de montaña. Su cuadro de aluminio ligero y resistente, combinado con su suspensión delantera, te permite afrontar cualquier terreno con confianza. Sus componentes de alta calidad garantizan un rendimiento excepcional en cada salida.",
    precio: 799.99,
    descuento: 10,
    categoria: "deportes",
    marca: "trek",
    imagen: "https://images.unsplash.com/photo-1544191696-15693072e0b5?w=400&h=400&fit=crop",
    especificaciones: [
      "Cuadro de aluminio 6061",
      "Suspensión delantera con 100mm de recorrido",
      "Cambio Shimano Deore de 12 velocidades",
      "Frenos de disco hidráulicos",
      "Ruedas de 29 pulgadas",
    ],
    tiendaId: 4,
    tipoVenta: "pedido",
    stock: 0,
    tiempoEntrega: "15-20 días hábiles",
  },
  {
    id: 10,
    nombre: "Cafetera Automática",
    descripcion: "Cafetera automática con molinillo integrado y 15 bares de presión",
    descripcionLarga:
      "La Cafetera Automática te permite disfrutar de un café de calidad profesional en la comodidad de tu hogar. Su molinillo integrado muele los granos justo antes de la preparación, garantizando el máximo aroma y sabor. Con sus 15 bares de presión, obtendrás un espresso perfecto con una crema densa y deliciosa.",
    precio: 249.99,
    descuento: 0,
    categoria: "hogar",
    marca: "delonghi",
    imagen: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop",
    especificaciones: [
      "Molinillo integrado con 13 niveles de molienda",
      "15 bares de presión",
      "Depósito de agua de 1.8L",
      "Panel de control táctil",
      "Sistema de autolimpieza",
    ],
    tiendaId: 3,
    tipoVenta: "directa",
    stock: 5,
    tiempoEntrega: "Inmediato",
  },
  {
    id: 11,
    nombre: "Vestido Elegante Noche",
    descripcion: "Vestido elegante para ocasiones especiales",
    descripcionLarga:
      "El Vestido Elegante Noche es la elección perfecta para tus eventos más especiales. Su diseño sofisticado y su tejido de alta calidad te harán destacar en cualquier ocasión. El corte favorecedor se adapta a tu figura, proporcionándote un look elegante y atemporal.",
    precio: 89.99,
    descuento: 0,
    categoria: "ropa",
    marca: "zara",
    imagen: "https://images.unsplash.com/photo-1566479179817-c0b5b4b8b1cc?w=400&h=400&fit=crop",
    especificaciones: [
      "Tejido de poliéster de alta calidad",
      "Forro interior",
      "Cierre con cremallera invisible",
      "Disponible en varios colores",
      "Tallas desde XS hasta XL",
    ],
    tiendaId: 2,
    tipoVenta: "directa",
    stock: 18,
    tiempoEntrega: "Inmediato",
  },
  {
    id: 12,
    nombre: "Set de Maquillaje Profesional",
    descripcion: "Set completo de maquillaje con paleta de sombras, base y labiales",
    descripcionLarga:
      "El Set de Maquillaje Profesional incluye todo lo que necesitas para crear looks impresionantes. La paleta de sombras con colores versátiles, la base de larga duración y los labiales de acabado perfecto te permiten expresar tu creatividad y realzar tu belleza natural.",
    precio: 79.99,
    descuento: 15,
    categoria: "belleza",
    marca: "maybelline",
    imagen: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop",
    especificaciones: [
      "Paleta de 24 sombras de ojos",
      "Base de maquillaje de larga duración",
      "3 labiales de acabado mate",
      "2 coloretes",
      "Brochas de aplicación incluidas",
    ],
    tiendaId: 5,
    tipoVenta: "directa",
    stock: 22,
    tiempoEntrega: "Inmediato",
  },
  // Productos de comida/delivery con imágenes reales
  {
    id: 13,
    nombre: "Pizza Margherita",
    descripcion: "Pizza clásica con tomate, mozzarella y albahaca fresca",
    descripcionLarga:
      "Nuestra Pizza Margherita es preparada con ingredientes frescos: salsa de tomate casera, mozzarella de búfala y albahaca fresca. Horneada en horno de leña para obtener la textura perfecta.",
    precio: 12.99,
    descuento: 0,
    categoria: "comida",
    marca: "casa",
    imagen: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&h=400&fit=crop",
    especificaciones: [
      "Masa artesanal fermentada 24h",
      "Mozzarella de búfala",
      "Tomate San Marzano",
      "Albahaca fresca",
      "Horneada en horno de leña",
    ],
    tiendaId: 7,
    tipoVenta: "delivery",
    stock: 999,
    tiempoEntrega: "30-45 minutos",
  },
  {
    id: 14,
    nombre: "Hamburguesa Gourmet",
    descripcion: "Hamburguesa de carne angus con queso cheddar y vegetales frescos",
    descripcionLarga:
      "Hamburguesa premium con carne angus de 200g, queso cheddar madurado, lechuga, tomate, cebolla caramelizada y nuestra salsa especial. Servida con papas fritas artesanales.",
    precio: 15.5,
    descuento: 10,
    categoria: "comida",
    marca: "casa",
    imagen: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=400&fit=crop",
    especificaciones: [
      "Carne angus 200g",
      "Queso cheddar madurado",
      "Pan brioche artesanal",
      "Vegetales frescos",
      "Incluye papas fritas",
    ],
    tiendaId: 8,
    tipoVenta: "delivery",
    stock: 999,
    tiempoEntrega: "25-35 minutos",
  },
  {
    id: 15,
    nombre: "Sushi Variado (20 piezas)",
    descripcion: "Selección de sushi fresco con salmón, atún y vegetales",
    descripcionLarga:
      "Bandeja de sushi variado con 20 piezas que incluye nigiri de salmón y atún, maki de pepino y aguacate, y california roll. Preparado por nuestro chef especializado.",
    precio: 24.99,
    descuento: 0,
    categoria: "comida",
    marca: "casa",
    imagen: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=400&fit=crop",
    especificaciones: [
      "20 piezas variadas",
      "Pescado fresco del día",
      "Arroz sushi premium",
      "Incluye wasabi y jengibre",
      "Preparado al momento",
    ],
    tiendaId: 9,
    tipoVenta: "delivery",
    stock: 999,
    tiempoEntrega: "40-50 minutos",
  },
  {
    id: 16,
    nombre: "Café Espresso Premium",
    descripcion: "Café espresso preparado con granos arábica de origen único",
    descripcionLarga:
      "Espresso preparado con granos arábica de Colombia, tostado artesanalmente. Perfecto para disfrutar en el local o para llevar.",
    precio: 3.5,
    descuento: 0,
    categoria: "bebidas",
    marca: "casa",
    imagen: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop",
    especificaciones: [
      "Granos arábica 100%",
      "Origen: Colombia",
      "Tostado artesanal",
      "Preparado al momento",
      "Disponible para llevar",
    ],
    tiendaId: 10,
    tipoVenta: "delivery",
    stock: 999,
    tiempoEntrega: "15-20 minutos",
  },
]
