export const tiendas = [
  {
    id: 1,
    nombre: "TechWorld",
    descripcion:
      "Tu tienda de tecnología de confianza. Especialistas en smartphones, laptops y accesorios tecnológicos de última generación.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Calle Tecnología 123, Madrid, España",
    ciudad: "Madrid",
    telefono: "+34 912 345 678",
    email: "contacto@techworld.com",
    calificacion: 4.8,
    totalReseñas: 1247,
    categorias: ["Electrónica", "Smartphones", "Laptops"],
    horarios: ["Lun - Vie: 9:00 - 20:00", "Sáb: 10:00 - 18:00", "Dom: Cerrado"],
    fechaRegistro: "Enero 2020",
    ventasTotales: 5420,
  },
  {
    id: 2,
    nombre: "Moda Urbana",
    descripcion:
      "Las últimas tendencias en moda urbana y streetwear. Ropa de calidad para hombres y mujeres que buscan estilo único.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Avenida Moda 456, Barcelona, España",
    ciudad: "Barcelona",
    telefono: "+34 934 567 890",
    email: "info@modaurbana.com",
    calificacion: 4.6,
    totalReseñas: 892,
    categorias: ["Ropa", "Streetwear", "Accesorios"],
    horarios: ["Lun - Sáb: 10:00 - 21:00", "Dom: 12:00 - 19:00"],
    fechaRegistro: "Marzo 2021",
    ventasTotales: 3280,
  },
  {
    id: 3,
    nombre: "Casa & Hogar",
    descripcion:
      "Todo lo que necesitas para hacer de tu casa un hogar. Decoración, muebles y electrodomésticos de calidad.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Plaza del Hogar 789, Valencia, España",
    ciudad: "Valencia",
    telefono: "+34 963 789 012",
    email: "ventas@casayhogar.com",
    calificacion: 4.7,
    totalReseñas: 654,
    categorias: ["Hogar", "Decoración", "Electrodomésticos"],
    horarios: ["Lun - Vie: 9:30 - 19:30", "Sáb: 10:00 - 20:00", "Dom: 11:00 - 17:00"],
    fechaRegistro: "Junio 2019",
    ventasTotales: 2150,
  },
  {
    id: 4,
    nombre: "SportZone",
    descripcion:
      "Equipamiento deportivo profesional y casual. Todo lo que necesitas para mantenerte activo y saludable.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Calle Deporte 321, Sevilla, España",
    ciudad: "Sevilla",
    telefono: "+34 954 321 654",
    email: "info@sportzone.com",
    calificacion: 4.9,
    totalReseñas: 1089,
    categorias: ["Deportes", "Fitness", "Outdoor"],
    horarios: ["Lun - Vie: 8:00 - 21:00", "Sáb - Dom: 9:00 - 20:00"],
    fechaRegistro: "Septiembre 2020",
    ventasTotales: 4670,
  },
  {
    id: 5,
    nombre: "Belleza Natural",
    descripcion:
      "Productos de belleza y cuidado personal con ingredientes naturales. Cuida tu piel de forma consciente.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Avenida Belleza 654, Bilbao, España",
    ciudad: "Bilbao",
    telefono: "+34 944 654 987",
    email: "contacto@bellezanatural.com",
    calificacion: 4.5,
    totalReseñas: 423,
    categorias: ["Belleza", "Cuidado Personal", "Natural"],
    horarios: ["Lun - Vie: 10:00 - 19:00", "Sáb: 10:00 - 18:00", "Dom: Cerrado"],
    fechaRegistro: "Febrero 2022",
    ventasTotales: 1890,
  },
  {
    id: 6,
    nombre: "Electro Premium",
    descripcion: "Electrodomésticos y electrónicos premium para el hogar moderno. Calidad y tecnología de vanguardia.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Calle Premium 987, Zaragoza, España",
    ciudad: "Zaragoza",
    telefono: "+34 976 987 321",
    email: "ventas@electropremium.com",
    calificacion: 4.8,
    totalReseñas: 756,
    categorias: ["Electrónica", "Electrodomésticos", "Smart Home"],
    horarios: ["Lun - Vie: 9:00 - 20:00", "Sáb: 10:00 - 19:00", "Dom: 11:00 - 16:00"],
    fechaRegistro: "Noviembre 2019",
    ventasTotales: 3450,
  },
  // Nuevas tiendas de comida
  {
    id: 7,
    nombre: "Pizzería Italiana",
    descripcion: "Auténtica pizza italiana preparada con ingredientes importados y recetas tradicionales.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Via Roma 123, Madrid, España",
    ciudad: "Madrid",
    telefono: "+34 911 234 567",
    email: "info@pizzeriaitaliana.com",
    calificacion: 4.7,
    totalReseñas: 892,
    categorias: ["Comida", "Pizza", "Italiana"],
    horarios: ["Lun - Dom: 12:00 - 23:00"],
    fechaRegistro: "Mayo 2021",
    ventasTotales: 2340,
  },
  {
    id: 8,
    nombre: "Burger House",
    descripcion: "Hamburguesas gourmet con ingredientes premium. La mejor carne y los sabores más auténticos.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Calle Burger 456, Barcelona, España",
    ciudad: "Barcelona",
    telefono: "+34 933 456 789",
    email: "pedidos@burgerhouse.com",
    calificacion: 4.6,
    totalReseñas: 1156,
    categorias: ["Comida", "Hamburguesas", "Americana"],
    horarios: ["Lun - Dom: 11:00 - 24:00"],
    fechaRegistro: "Agosto 2020",
    ventasTotales: 3890,
  },
  {
    id: 9,
    nombre: "Sushi Zen",
    descripcion: "Sushi fresco y auténtico preparado por chefs especializados. Tradición japonesa en cada bocado.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Avenida Zen 789, Valencia, España",
    ciudad: "Valencia",
    telefono: "+34 962 789 123",
    email: "reservas@sushizen.com",
    calificacion: 4.9,
    totalReseñas: 567,
    categorias: ["Comida", "Sushi", "Japonesa"],
    horarios: ["Mar - Dom: 13:00 - 23:00", "Lun: Cerrado"],
    fechaRegistro: "Enero 2022",
    ventasTotales: 1670,
  },
  {
    id: 10,
    nombre: "Café Central",
    descripcion: "Café de especialidad con granos seleccionados. El lugar perfecto para disfrutar un buen café.",
    logo: "/placeholder.svg?height=100&width=100",
    imagenPortada: "/placeholder.svg?height=300&width=800",
    direccion: "Plaza Central 321, Sevilla, España",
    ciudad: "Sevilla",
    telefono: "+34 955 321 654",
    email: "hola@cafecentral.com",
    calificacion: 4.8,
    totalReseñas: 734,
    categorias: ["Bebidas", "Café", "Desayunos"],
    horarios: ["Lun - Vie: 7:00 - 20:00", "Sáb - Dom: 8:00 - 21:00"],
    fechaRegistro: "Abril 2020",
    ventasTotales: 4520,
  },
]
